#!/usr/bin/env python3
"""Compile the Sigma rules in detections/ to Splunk SPL.

Sigma is the source of truth. This script renders each rule through the pySigma
Splunk backend and writes the result to detections/generated/<rule>.spl. Generated
files are overwritten on every run and are not edited by hand -- deployment tweaks
live in detections/tuned/ instead.

Two pipelines are chained. `sysmon` resolves the rules' `category: process_creation`
logsource to the Sysmon channel and EventCode; `splunk_windows` then renders the
Windows logsource as Splunk field terms. Without the first, category-based rules
compile with no log-source scoping at all.

Usage:
    ./venv/bin/python convert.py           # regenerate all rules
    ./venv/bin/python convert.py --check   # fail if anything is out of date (CI)
"""

import argparse
import sys
from pathlib import Path

from sigma.backends.splunk import SplunkBackend
from sigma.collection import SigmaCollection
from sigma.pipelines.splunk import splunk_windows_pipeline
from sigma.pipelines.sysmon import sysmon_pipeline

REPO = Path(__file__).parent
RULES = REPO / "detections"
OUTPUT = RULES / "generated"

HEADER = """\
``` AUTO-GENERATED by convert.py from {source} -- do not edit.
    Backend: pySigma splunk | Pipelines: sysmon + splunk_windows
    Deployment-tuned variant: {tuned} ```
"""


def compile_rule(path: Path) -> str:
    """Render one Sigma rule to SPL, including the provenance header."""
    pipeline = sysmon_pipeline() + splunk_windows_pipeline()
    backend = SplunkBackend(processing_pipeline=pipeline)
    queries = backend.convert(SigmaCollection.load_ruleset([path]))
    header = HEADER.format(
        source=path.relative_to(REPO),
        tuned=(RULES / "tuned" / f"{path.stem}.spl").relative_to(REPO),
    )
    return header + "\n".join(queries) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated output is current instead of writing it",
    )
    args = parser.parse_args()

    rules = sorted(RULES.glob("*.yml"))
    if not rules:
        print(f"No Sigma rules found in {RULES}/", file=sys.stderr)
        return 1

    OUTPUT.mkdir(exist_ok=True)
    stale = []
    for rule in rules:
        target = OUTPUT / f"{rule.stem}.spl"
        spl = compile_rule(rule)
        if args.check:
            current = target.read_text() if target.exists() else None
            state = "OK" if current == spl else "STALE"
            if current != spl:
                stale.append(target)
        else:
            target.write_text(spl)
            state = "wrote"
        print(f"{state:>5}  {rule.name} -> {target.relative_to(REPO)}")

    if stale:
        print(
            f"\n{len(stale)} generated file(s) out of date; run: python convert.py",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
